backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sort: "date:desc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Current", name: "current", widget: "hidden", default: "post"}
      - {label: "Navigation", name: "navigation", widget: "hidden", default: "True"}
      - {label: "Class", name: "class", widget: "hidden", default: "post-template"}
      - {label: "Subclass", name: "subclass", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "TAG", name: "tags", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}